name: ci-customize-server

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: tester des commandes
        env:
          UNE_VAR: toto
        run: |
          echo ${UNE_VAR}
          docker version
      - name: Get pbf file
        run: wget http://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf  
      - name: pre-process
        run: docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/berlin-latest.osm.pbf