name: ci-customize-server

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: tester des commandes
        env:
          UNE_VAR: toto
        run: |
          echo ${UNE_VAR}
          echo "...... hello!"