name: ci-customize-server

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: tester des commandes
        env:
          UNE_VAR: toto
        run: |
          echo ${UNE_VAR}
          docker version
      
      - name: Test pull
        run: |
          docker run -t -i -p 5000:5000 -v "${PWD}:/data" ghcr.io/achile73/osrm-serveur-de-calcul:latest osrm-routed --algorithm mld /data/berlin-latest.osrm
    
      - name: Get pbf file
        run: wget http://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf  
      - name: Pre-process pbf file
        run: |
          docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/berlin-latest.osm.pbf
          docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-partition /data/berlin-latest.osrm
          docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-customize /data/berlin-latest.osrm
          cp berlin-latest.osrm osrm-files/
          ls -als osrm-files/
      
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: Build and push to ghcr
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          context: .
          file: ./Dockerfile
          push: true
          #tags: osrm:latest
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
          registry: ghcr.io
          #repository: achile73/demos/demo-backend
          tag_with_ref: true
      