name: ci-customize-server

on:
  push:
    branches: master

jobs:
  test-Maven:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-adoptopenjdk-11
    steps:  
    - uses: actions/checkout@v2
    - name: What OS is running
      run: uname -a
    - name: What java version do we have
      run: java -version
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: tester des commandes
        env:
          UNE_VAR: toto
        run: |
          echo ${UNE_VAR}
          echo "...... hello!"
          docker version
        run: docker version
      - name: pre-process
        run: docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract